// Admin panel HTML.
import { e, money } from "./lib.js";
import { STATUS_LABELS } from "./views.js";

const ALL_STATUSES = ["placed", "confirmed", "packed", "shipped", "out_for_delivery", "delivered", "cancelled"];

function ahead(title) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${e(title)} · Admin</title><script src="https://cdn.tailwindcss.com"></script>
<script>tailwind.config={theme:{extend:{colors:{ink:'#23190f',clay:{DEFAULT:'#bf5836',dark:'#9c4527'}}}}}</script>
<style>.input{width:100%;border:1px solid #e5e7eb;border-radius:.6rem;padding:.6rem .8rem;font-size:.9rem;outline:none}.input:focus{border-color:#23190f}.lbl{display:block;font-size:.72rem;font-weight:600;color:#6b7280;margin-bottom:.3rem;text-transform:uppercase;letter-spacing:.04em}[x-cloak]{display:none}</style>
<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script></head>`;
}

export function adminLoginView(ctx) {
  return `${ahead("Admin Login")}<body class="bg-ink min-h-screen flex items-center justify-center px-4 font-sans">
  <div class="w-full max-w-sm"><div class="text-center mb-6"><div class="font-bold text-3xl text-white" style="font-family:Georgia,serif">Aswhani<span style="color:#bf5836">.</span></div><p class="text-gray-400 text-sm mt-1">Admin Panel</p></div>
  ${ctx.flash ? `<div class="bg-red-500/20 text-red-200 px-4 py-2 text-sm mb-3 rounded-lg">${e(ctx.flash.msg)}</div>` : ""}
  <form method="post" class="bg-white rounded-2xl p-7 space-y-4"><input type="hidden" name="csrf" value="${e(ctx.csrf)}">
    <input name="email" type="email" placeholder="Admin email" required class="input"><input name="password" type="password" placeholder="Password" required class="input">
    <button class="w-full bg-ink text-white text-[12px] uppercase tracking-[0.2em] py-3.5 rounded-full hover:bg-clay">Log In</button></form>
  <p class="text-center text-gray-500 text-xs mt-4"><a href="/" class="hover:text-white">← Back to store</a></p></div></body></html>`;
}

function shell(ctx, title, body) {
  const nav = [["", "Dashboard", "▦"], ["products", "Products", "👕"], ["orders", "Orders", "📦"], ["returns", "Returns", "↩"], ["reports", "Reports", "📈"], ["coupons", "Coupons", "🏷"], ["reviews", "Reviews", "★"], ["pages", "Pages", "📄"], ["newsletter", "Newsletter", "✉"], ["messages", "Messages", "💬"], ["settings", "Settings", "⚙"]];
  const links = nav.map(([slug, label, icon]) => {
    const href = "/admin/" + slug;
    const active = ctx.path === href || (slug === "" && ctx.path === "/admin/");
    return `<a href="${href}" class="flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm ${active ? "bg-white/10 text-white" : "hover:bg-white/5"}">${icon} ${label}</a>`;
  }).join("");
  return `${ahead(title)}<body class="bg-gray-50 text-ink font-sans" x-data="{sb:false}"><div class="flex min-h-screen">
    <aside class="fixed lg:static inset-y-0 left-0 w-64 bg-ink text-gray-300 z-40 transform lg:translate-x-0 transition" :class="sb?'translate-x-0':'-translate-x-full'">
      <div class="p-5 border-b border-white/10"><span class="font-bold text-xl text-white" style="font-family:Georgia,serif">Aswhani<span class="text-clay">.</span></span> <span class="text-xs text-gray-400">admin</span></div>
      <nav class="p-3 space-y-1">${links}</nav>
      <div class="absolute bottom-0 left-0 right-0 p-3 border-t border-white/10"><a href="/" class="block px-3 py-2 text-sm hover:text-white">↗ View Store</a><a href="/admin/logout" class="block px-3 py-2 text-sm hover:text-white">Log out</a></div>
    </aside>
    <div x-show="sb" @click="sb=false" class="fixed inset-0 bg-black/40 z-30 lg:hidden"></div>
    <div class="flex-1 min-w-0"><header class="bg-white border-b border-gray-100 sticky top-0 z-20 px-4 sm:px-6 h-14 flex items-center justify-between"><button @click="sb=true" class="lg:hidden">☰</button><h1 class="font-semibold">${e(title)}</h1><span class="text-sm text-gray-500">Admin</span></header>
    ${ctx.flash ? `<div class="px-4 sm:px-6 pt-4"><div class="${ctx.flash.type === "error" ? "bg-red-50 text-red-800" : "bg-green-50 text-green-800"} rounded-xl px-4 py-2.5 text-sm">${e(ctx.flash.msg)}</div></div>` : ""}
    <main class="p-4 sm:p-6">${body}</main></div></div></body></html>`;
}

export function dashboardView(ctx, { stats, recent, low }) {
  const cards = [["Total Orders", stats.orders, "📦", "bg-blue-50 text-blue-700"], ["Revenue", money(stats.revenue), "💰", "bg-green-50 text-green-700"], ["Products", stats.products, "👕", "bg-purple-50 text-purple-700"], ["Customers", stats.customers, "👥", "bg-amber-50 text-amber-700"]];
  return shell(ctx, "Dashboard", `<div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
    ${cards.map(([l, v, i, c]) => `<div class="bg-white rounded-2xl p-5 border border-gray-100"><div class="w-10 h-10 rounded-xl ${c} flex items-center justify-center text-lg mb-3">${i}</div><p class="text-2xl font-bold">${v}</p><p class="text-sm text-gray-500">${l}</p></div>`).join("")}</div>
    <div class="grid lg:grid-cols-2 gap-4"><div class="bg-white rounded-2xl border border-gray-100 overflow-hidden"><div class="px-5 py-4 border-b border-gray-100 flex justify-between"><h2 class="font-semibold">Recent Orders</h2><a href="/admin/orders" class="text-sm text-clay">View all</a></div><table class="w-full text-sm"><tbody>
    ${recent.length ? recent.map((o) => `<tr class="border-b border-gray-50 last:border-0"><td class="px-5 py-3"><a href="/admin/orders/${e(o.order_no)}" class="font-medium hover:text-clay">${e(o.order_no)}</a><div class="text-xs text-gray-400">${e(o.customer_name)}</div></td><td class="px-5 py-3 text-right">${money(o.total)}</td><td class="px-5 py-3 text-right"><span class="text-xs px-2 py-0.5 rounded-full bg-gray-100">${STATUS_LABELS[o.status]}</span></td></tr>`).join("") : `<tr><td class="px-5 py-6 text-gray-400 text-center">No orders yet.</td></tr>`}</tbody></table></div>
    <div class="bg-white rounded-2xl border border-gray-100 overflow-hidden"><div class="px-5 py-4 border-b border-gray-100"><h2 class="font-semibold">Low Stock</h2></div><table class="w-full text-sm"><tbody>
    ${low.length ? low.map((p) => `<tr class="border-b border-gray-50 last:border-0"><td class="px-5 py-3"><a href="/admin/products/${p.id}" class="hover:text-clay">${e(p.name)}</a></td><td class="px-5 py-3 text-right"><span class="text-xs px-2 py-0.5 rounded-full ${p.stock === 0 ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700"}">${p.stock} left</span></td></tr>`).join("") : `<tr><td class="px-5 py-6 text-gray-400 text-center">All stocked. 👍</td></tr>`}</tbody></table></div></div>`);
}

export function adminProductsView(ctx, { products }) {
  return shell(ctx, "Products", `<div class="flex justify-end gap-2 mb-5"><a href="/admin/import" class="border border-ink text-sm px-5 py-2.5 rounded-full hover:bg-ink hover:text-white">⬆ Import CSV</a><a href="/admin/products/new" class="bg-ink text-white text-sm px-5 py-2.5 rounded-full hover:bg-clay">+ Add Product</a></div>
    <div class="bg-white rounded-2xl border border-gray-100 overflow-x-auto"><table class="w-full text-sm min-w-[600px]"><thead class="bg-gray-50 text-gray-500 text-left"><tr><th class="px-4 py-3">Product</th><th class="px-4 py-3">Price</th><th class="px-4 py-3">Stock</th><th class="px-4 py-3">Status</th><th></th></tr></thead><tbody>
    ${products.map((p) => `<tr class="border-t border-gray-50"><td class="px-4 py-3"><div class="flex items-center gap-3"><img src="${e(p.image)}" class="w-10 h-12 object-cover rounded-lg"><div><p class="font-medium">${e(p.name)}</p><p class="text-xs text-gray-400">${e(p.sizes)}</p></div></div></td><td class="px-4 py-3">${money(p.price)}</td><td class="px-4 py-3"><span class="${p.stock === 0 ? "text-red-600" : p.stock <= 5 ? "text-amber-600" : ""}">${p.stock}</span></td><td class="px-4 py-3">${p.is_active ? '<span class="text-xs px-2 py-0.5 rounded-full bg-green-100 text-green-700">Active</span>' : '<span class="text-xs px-2 py-0.5 rounded-full bg-gray-200">Hidden</span>'}</td><td class="px-4 py-3 text-right whitespace-nowrap"><a href="/admin/products/${p.id}" class="text-clay hover:underline">Edit</a> <form action="/admin/products/${p.id}/delete" method="post" class="inline" onsubmit="return confirm('Delete?')"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><button class="text-gray-400 hover:text-red-500 ml-2">Delete</button></form></td></tr>`).join("")}
    </tbody></table></div>`);
}

export function productFormView(ctx, { p, categories, variantMap, gallery }) {
  const opts = categories.map((c) => `<option value="${c.id}" ${p && p.category_id === c.id ? "selected" : ""}>${e(c.name)}</option>`).join("");
  const galleryBlock = p ? `<div class="bg-white rounded-2xl border border-gray-100 p-6"><h3 class="font-semibold mb-1">Gallery images</h3><p class="text-xs text-gray-400 mb-4">Extra thumbnails on the product page.</p><div class="flex flex-wrap gap-3 mb-4">${(gallery || []).map((im) => `<div class="relative w-20 h-24"><img src="${e(im.url)}" class="w-full h-full object-cover rounded-lg"><form action="/admin/products/image/${im.id}/delete" method="post" class="absolute -top-2 -right-2"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><button class="bg-red-500 text-white w-5 h-5 rounded-full text-xs">×</button></form></div>`).join("") || '<p class="text-sm text-gray-400">No gallery images yet.</p>'}</div><form action="/admin/products/${p.id}/image/add" method="post" enctype="multipart/form-data" class="flex flex-wrap items-center gap-3"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><input name="image_file" type="file" accept="image/*" class="text-sm"><span class="text-gray-400 text-sm">or</span><input name="image_url" placeholder="image URL" class="input flex-1 min-w-[180px]"><button class="bg-ink text-white px-5 py-2 rounded-full text-sm hover:bg-clay">Add</button></form></div>` : "";
  return shell(ctx, p ? "Edit Product" : "New Product", `<script>window.__pvar=${JSON.stringify(variantMap || {})};
  function variantEditor(sizesRaw,colorsRaw,existing){return{sizesRaw:sizesRaw,colorsRaw:colorsRaw,existing:existing||{},get sizes(){return this.sizesRaw.split(',').map(s=>s.trim()).filter(Boolean)},get colorList(){var c=this.colorsRaw.split(',').map(s=>s.trim()).filter(Boolean);return c.length?c:['']},get combos(){var out=[],self=this;if(!this.sizes.length&&this.colorList.length===1&&this.colorList[0]==='')return out;(this.sizes.length?this.sizes:['']).forEach(function(s){self.colorList.forEach(function(c){out.push({key:s+'|'+c,label:(s||'One size')+(c?' · '+c:'')})})});return out},val:function(k){return (k in this.existing)?this.existing[k]:0}}}</script>
  <form method="post" enctype="multipart/form-data" class="max-w-3xl space-y-5" x-data="variantEditor('${e(p ? p.sizes : "S,M,L,XL")}','${e(p ? p.colors : "")}',window.__pvar)"><input type="hidden" name="csrf" value="${e(ctx.csrf)}">
    <div class="bg-white rounded-2xl border border-gray-100 p-6 grid sm:grid-cols-2 gap-4">
      <div class="sm:col-span-2"><label class="lbl">Name *</label><input name="name" value="${e(p ? p.name : "")}" required class="input"></div>
      <div class="sm:col-span-2"><label class="lbl">Description</label><textarea name="description" rows="3" class="input">${e(p ? p.description : "")}</textarea></div>
      <div class="sm:col-span-2"><label class="lbl">Size chart (popup on product page)</label><textarea name="size_chart" rows="2" placeholder="S = chest 38in · M = 40in …" class="input">${e(p ? p.size_chart : "")}</textarea></div>
      <div><label class="lbl">Category</label><select name="category_id" class="input"><option value="">— none —</option>${opts}</select></div>
      <div><label class="lbl">Stock (only if no variants below)</label><input name="stock" type="number" value="${p ? p.stock : 100}" class="input"></div>
      <div><label class="lbl">Price (₹) *</label><input name="price" type="number" value="${p ? p.price : ""}" required class="input"></div>
      <div><label class="lbl">MRP (₹)</label><input name="mrp" type="number" value="${p && p.mrp ? p.mrp : ""}" class="input"></div>
      <div><label class="lbl">Sizes (CSV)</label><input name="sizes" x-model="sizesRaw" class="input"></div>
      <div><label class="lbl">Colours (CSV)</label><input name="colors" x-model="colorsRaw" class="input"></div>
    </div>
    <div class="bg-white rounded-2xl border border-gray-100 p-6"><h3 class="font-semibold">Stock per size / colour</h3><p class="text-xs text-gray-400 mb-4">Real inventory. Edit sizes/colours above and the grid updates. The simple "Stock" is only used when there are no variants.</p>
      <template x-if="combos.length"><div class="grid sm:grid-cols-2 gap-2"><template x-for="cm in combos" :key="cm.key"><label class="flex items-center justify-between gap-3 border border-gray-100 rounded-lg px-3 py-2"><span class="text-sm" x-text="cm.label"></span><input type="number" min="0" class="input !w-24 text-right" :name="'vstock['+cm.key+']'" :value="val(cm.key)"></label></template></div></template>
      <template x-if="!combos.length"><p class="text-sm text-gray-400">No sizes/colours — using the simple Stock field.</p></template></div>
    <div class="bg-white rounded-2xl border border-gray-100 p-6 space-y-4"><h3 class="font-semibold">Main Image</h3>${p && p.image ? `<img src="${e(p.image)}" class="w-24 h-28 object-cover rounded-xl">` : ""}<div><label class="lbl">Upload image (stored in R2)</label><input name="image_file" type="file" accept="image/*" class="block text-sm"></div><div><label class="lbl">…or paste image URL</label><input name="image_url" value="${e(p && p.image && p.image.startsWith("http") ? p.image : "")}" placeholder="https://…" class="input"></div></div>
    <label class="flex items-center gap-2 bg-white rounded-2xl border border-gray-100 p-6"><input type="checkbox" name="is_active" ${!p || p.is_active ? "checked" : ""}> Active (visible in store)</label>
    <div class="flex gap-3"><button class="bg-ink text-white px-7 py-3 rounded-full hover:bg-clay">${p ? "Save Changes" : "Create Product"}</button><a href="/admin/products" class="px-7 py-3 rounded-full border border-gray-200">Cancel</a></div>
  </form>${galleryBlock}`);
}

export function adminOrdersView(ctx, { orders, status }) {
  const tabs = ["", ...ALL_STATUSES].map((s) => `<a href="/admin/orders${s ? "?status=" + s : ""}" class="px-4 py-1.5 rounded-full ${(status || "") === s ? "bg-ink text-white" : "bg-white border border-gray-200"}">${s ? STATUS_LABELS[s] : "All"}</a>`).join("");
  return shell(ctx, "Orders", `<div class="flex gap-2 flex-wrap mb-5 text-sm">${tabs}</div>
    <div class="bg-white rounded-2xl border border-gray-100 overflow-x-auto"><table class="w-full text-sm min-w-[640px]"><thead class="bg-gray-50 text-gray-500 text-left"><tr><th class="px-4 py-3">Order</th><th class="px-4 py-3">Customer</th><th class="px-4 py-3">Date</th><th class="px-4 py-3">Total</th><th class="px-4 py-3">Payment</th><th class="px-4 py-3">Status</th></tr></thead><tbody>
    ${orders.length ? orders.map((o) => `<tr class="border-t border-gray-50 hover:bg-gray-50 cursor-pointer" onclick="location.href='/admin/orders/${e(o.order_no)}'"><td class="px-4 py-3 font-medium text-clay">${e(o.order_no)}</td><td class="px-4 py-3">${e(o.customer_name)}<div class="text-xs text-gray-400">${e(o.phone)}</div></td><td class="px-4 py-3 text-gray-500">${e((o.created_at || "").slice(0, 16).replace("T", " "))}</td><td class="px-4 py-3 font-medium">${money(o.total)}</td><td class="px-4 py-3 text-xs">${e((o.payment_method || "").toUpperCase())} <span class="px-2 py-0.5 rounded-full ${o.payment_status === "paid" ? "bg-green-100 text-green-700" : "bg-amber-100 text-amber-700"}">${e(o.payment_status)}</span></td><td class="px-4 py-3"><span class="text-xs px-2 py-0.5 rounded-full bg-gray-100">${STATUS_LABELS[o.status]}</span></td></tr>`).join("") : `<tr><td colspan="6" class="px-4 py-10 text-center text-gray-400">No orders.</td></tr>`}
    </tbody></table></div>`);
}

export function couponsView(ctx, { coupons }) {
  const tag = (txt) => `<span class="inline-block text-[10px] px-2 py-0.5 rounded-full bg-clay/10 text-clay font-medium">${txt}</span>`;
  return shell(ctx, "Coupons", `<div class="grid lg:grid-cols-3 gap-5">
    <form method="post" class="bg-white rounded-2xl border border-gray-100 p-6 space-y-3 h-max"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><h3 class="font-semibold">Create Coupon</h3><input name="code" placeholder="CODE" required class="input uppercase"><select name="kind" class="input"><option value="percent">Percent (%) off</option><option value="flat">Flat (₹) off</option></select><input name="value" type="number" placeholder="Value" required class="input"><input name="min_order" type="number" value="0" placeholder="Min order ₹" class="input"><div><label class="lbl">Expires on (optional)</label><input name="expires_at" type="date" class="input"></div><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="first_order_only" value="1"> First order only</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="once_per_user" value="1"> One use per customer</label><button class="w-full bg-ink text-white py-2.5 rounded-full text-sm hover:bg-clay">Create</button></form>
    <div class="lg:col-span-2 bg-white rounded-2xl border border-gray-100 overflow-x-auto"><table class="w-full text-sm min-w-[520px]"><thead class="bg-gray-50 text-gray-500 text-left"><tr><th class="px-4 py-3">Code</th><th class="px-4 py-3">Discount</th><th class="px-4 py-3">Min</th><th class="px-4 py-3">Rules</th><th class="px-4 py-3">Status</th><th></th></tr></thead><tbody>
    ${coupons.length ? coupons.map((c) => `<tr class="border-t border-gray-50"><td class="px-4 py-3 font-mono font-medium">${e(c.code)}</td><td class="px-4 py-3">${c.kind === "percent" ? c.value + "%" : money(c.value)}</td><td class="px-4 py-3">${money(c.min_order)}</td><td class="px-4 py-3 space-x-1">${c.first_order_only ? tag("First-order") : ""}${c.once_per_user ? tag("1/user") : ""}${c.expires_at ? tag("exp " + e(c.expires_at)) : ""}${!c.first_order_only && !c.once_per_user && !c.expires_at ? '<span class="text-gray-300">—</span>' : ""}</td><td class="px-4 py-3"><form action="/admin/coupons/${c.id}/toggle" method="post" class="inline"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><button class="text-xs px-2 py-0.5 rounded-full ${c.is_active ? "bg-green-100 text-green-700" : "bg-gray-200"}">${c.is_active ? "Active" : "Inactive"}</button></form></td><td class="px-4 py-3 text-right"><form action="/admin/coupons/${c.id}/delete" method="post"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><button class="text-gray-400 hover:text-red-500">Delete</button></form></td></tr>`).join("") : `<tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">No coupons.</td></tr>`}
    </tbody></table></div></div>`);
}

export function reviewsView(ctx, { reviews }) {
  return shell(ctx, "Reviews", `<div class="bg-white rounded-2xl border border-gray-100 overflow-x-auto"><table class="w-full text-sm min-w-[600px]"><thead class="bg-gray-50 text-gray-500 text-left"><tr><th class="px-4 py-3">Product</th><th class="px-4 py-3">By</th><th class="px-4 py-3">Rating</th><th class="px-4 py-3">Comment</th><th></th></tr></thead><tbody>
    ${reviews.length ? reviews.map((r) => `<tr class="border-t border-gray-50"><td class="px-4 py-3">${e(r.product_name || "")}</td><td class="px-4 py-3">${e(r.name)}</td><td class="px-4 py-3 text-clay">${"★".repeat(r.rating)}</td><td class="px-4 py-3 text-gray-600">${e(r.comment || "")}</td><td class="px-4 py-3 text-right"><form action="/admin/reviews/${r.id}/delete" method="post"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><button class="text-gray-400 hover:text-red-500">Delete</button></form></td></tr>`).join("") : `<tr><td colspan="5" class="px-4 py-10 text-center text-gray-400">No reviews yet.</td></tr>`}
    </tbody></table></div>`);
}

export function returnsView(ctx, { returns }) {
  const ST = ["requested", "approved", "rejected", "completed"];
  return shell(ctx, "Returns", `<div class="bg-white rounded-2xl border border-gray-100 overflow-x-auto"><table class="w-full text-sm min-w-[680px]"><thead class="bg-gray-50 text-gray-500 text-left"><tr><th class="px-4 py-3">Order</th><th class="px-4 py-3">Type</th><th class="px-4 py-3">Reason</th><th class="px-4 py-3">Status</th></tr></thead><tbody>
    ${returns.length ? returns.map((r) => `<tr class="border-t border-gray-50"><td class="px-4 py-3"><a href="/admin/orders/${e(r.order_no)}" class="text-clay font-medium">${e(r.order_no)}</a></td><td class="px-4 py-3 capitalize">${e(r.kind)}</td><td class="px-4 py-3 text-gray-600">${e(r.reason || "—")}</td><td class="px-4 py-3"><form method="post" class="flex items-center gap-2"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><input type="hidden" name="id" value="${r.id}"><select name="status" class="input !py-1 text-xs">${ST.map((s) => `<option value="${s}" ${r.status === s ? "selected" : ""}>${s}</option>`).join("")}</select><button class="text-xs bg-ink text-white px-3 py-1 rounded-full">Update</button></form></td></tr>`).join("") : `<tr><td colspan="4" class="px-4 py-10 text-center text-gray-400">No return requests.</td></tr>`}
    </tbody></table></div>`);
}

export function pagesView(ctx, { pages }) {
  return shell(ctx, "Pages", `<div class="flex justify-end mb-5"><a href="/admin/pages/new" class="bg-ink text-white text-sm px-5 py-2.5 rounded-full hover:bg-clay">+ New Page</a></div><div class="bg-white rounded-2xl border border-gray-100 overflow-hidden"><table class="w-full text-sm"><thead class="bg-gray-50 text-gray-500 text-left"><tr><th class="px-4 py-3">Title</th><th class="px-4 py-3">URL</th><th></th></tr></thead><tbody>
    ${pages.map((pg) => `<tr class="border-t border-gray-50"><td class="px-4 py-3 font-medium">${e(pg.title)}</td><td class="px-4 py-3 text-gray-400">/page/${e(pg.slug)}</td><td class="px-4 py-3 text-right"><a href="/admin/pages/${pg.id}" class="text-clay">Edit</a> <form action="/admin/pages/${pg.id}/delete" method="post" class="inline"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><button class="text-gray-400 hover:text-red-500 ml-2">Delete</button></form></td></tr>`).join("")}
    </tbody></table></div>`);
}
export function pageFormView(ctx, { page }) {
  return shell(ctx, page ? "Edit Page" : "New Page", `<form method="post" class="max-w-3xl space-y-5"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><div class="bg-white rounded-2xl border border-gray-100 p-6 space-y-4"><div><label class="lbl">Title *</label><input name="title" value="${e(page ? page.title : "")}" required class="input"></div>${page ? "" : `<div><label class="lbl">Slug (optional)</label><input name="slug" placeholder="auto" class="input"></div>`}<div><label class="lbl">Content (HTML)</label><textarea name="body" rows="12" class="input font-mono text-xs">${e(page ? page.body : "")}</textarea></div><label class="flex items-center gap-2"><input type="checkbox" name="in_footer" ${!page || page.in_footer ? "checked" : ""}> Show in footer</label></div><div class="flex gap-3"><button class="bg-ink text-white px-7 py-3 rounded-full hover:bg-clay">${page ? "Save" : "Create"}</button><a href="/admin/pages" class="px-7 py-3 rounded-full border border-gray-200">Cancel</a></div></form>`);
}

export function reportsView(ctx, { days, maxrev, top }) {
  return shell(ctx, "Reports", `<div class="bg-white rounded-2xl border border-gray-100 p-6 mb-5"><h2 class="font-semibold mb-4">Revenue — last 14 days</h2><div class="flex items-end gap-2 h-48">
    ${days.map((d) => `<div class="flex-1 flex flex-col items-center justify-end h-full group"><div class="text-[10px] text-gray-500 mb-1 opacity-0 group-hover:opacity-100">${money(d.rev)}</div><div class="w-full bg-clay/80 hover:bg-clay rounded-t" style="height:${((d.rev / maxrev) * 100).toFixed(1)}%;min-height:2px"></div><div class="text-[9px] text-gray-400 mt-1">${e(d.label)}</div></div>`).join("")}
    </div></div>
    <div class="bg-white rounded-2xl border border-gray-100 overflow-hidden"><div class="px-5 py-4 border-b border-gray-100"><h2 class="font-semibold">Top Sellers</h2></div><table class="w-full text-sm"><thead class="bg-gray-50 text-gray-500 text-left"><tr><th class="px-4 py-3">Product</th><th class="px-4 py-3 text-right">Units</th><th class="px-4 py-3 text-right">Revenue</th></tr></thead><tbody>
    ${top.length ? top.map((t) => `<tr class="border-t border-gray-50"><td class="px-4 py-3">${e(t.name)}</td><td class="px-4 py-3 text-right">${t.q}</td><td class="px-4 py-3 text-right">${money(t.amt)}</td></tr>`).join("") : `<tr><td colspan="3" class="px-4 py-10 text-center text-gray-400">No sales yet.</td></tr>`}
    </tbody></table></div>`);
}

export function newsletterView(ctx, { subs }) {
  return shell(ctx, "Newsletter", `<div class="flex justify-between items-center mb-5"><p class="text-sm text-gray-500">${subs.length} subscriber(s)</p><a href="/admin/newsletter/export.csv" class="bg-green-600 text-white text-sm px-5 py-2.5 rounded-full hover:bg-green-700">⬇ Export CSV</a></div><div class="bg-white rounded-2xl border border-gray-100 overflow-hidden"><table class="w-full text-sm"><thead class="bg-gray-50 text-gray-500 text-left"><tr><th class="px-4 py-3">Email</th><th class="px-4 py-3">Subscribed</th></tr></thead><tbody>${subs.length ? subs.map((s) => `<tr class="border-t border-gray-50"><td class="px-4 py-3">${e(s.email)}</td><td class="px-4 py-3 text-gray-500">${e((s.created_at || "").slice(0, 10))}</td></tr>`).join("") : `<tr><td colspan="2" class="px-4 py-10 text-center text-gray-400">No subscribers.</td></tr>`}</tbody></table></div>`);
}
export function messagesView(ctx, { messages }) {
  return shell(ctx, "Messages", `<div class="space-y-3">${messages.length ? messages.map((m) => `<div class="bg-white rounded-2xl border border-gray-100 p-5"><div class="flex items-center justify-between"><div><span class="font-medium">${e(m.name)}</span> <span class="text-gray-400 text-sm">${e(m.email || "")}</span></div><span class="text-xs text-gray-400">${e((m.created_at || "").slice(0, 16).replace("T", " "))}</span></div><p class="text-sm text-gray-700 mt-2 whitespace-pre-wrap">${e(m.message)}</p></div>`).join("") : `<div class="bg-white rounded-2xl border border-gray-100 p-10 text-center text-gray-400">No messages.</div>`}</div>`);
}
export function importView(ctx) {
  return shell(ctx, "Import Products", `<div class="max-w-2xl space-y-5"><form method="post" enctype="multipart/form-data" class="bg-white rounded-2xl border border-gray-100 p-6 space-y-4"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><p class="text-sm text-gray-500">Upload a CSV to add/update many products. Matched by <b>name</b>.</p><input name="csv_file" type="file" accept=".csv" required class="block text-sm"><button class="bg-ink text-white px-7 py-3 rounded-full hover:bg-clay">Import</button></form><div class="bg-white rounded-2xl border border-gray-100 p-6 text-sm"><h3 class="font-semibold mb-2">CSV columns</h3><pre class="bg-gray-50 rounded-lg p-3 overflow-x-auto text-xs">name,price,mrp,description,sizes,colors,stock,image,category
Cotton Tee,699,1199,Soft tee,"S,M,L","Black,White",50,https://...,Men</pre><p class="text-gray-400 mt-2 text-xs">Only name + price required. category must match an existing category name.</p></div></div>`);
}
export function settingsView(ctx, { v }) {
  const f = (k) => e(v[k] || "");
  return shell(ctx, "Settings", `<form method="post" class="max-w-2xl space-y-5"><input type="hidden" name="csrf" value="${e(ctx.csrf)}">
    <div class="bg-white rounded-2xl border border-gray-100 p-6 grid sm:grid-cols-2 gap-4"><h3 class="font-semibold sm:col-span-2">Store</h3><div class="sm:col-span-2"><label class="lbl">Store name</label><input name="store_name" value="${f("store_name")}" class="input"></div><div class="sm:col-span-2"><label class="lbl">Tagline</label><input name="store_tagline" value="${f("store_tagline")}" class="input"></div><div><label class="lbl">Support email</label><input name="support_email" value="${f("support_email")}" class="input"></div><div><label class="lbl">Support phone</label><input name="support_phone" value="${f("support_phone")}" class="input"></div></div>
    <div class="bg-white rounded-2xl border border-gray-100 p-6 grid sm:grid-cols-2 gap-4"><h3 class="font-semibold sm:col-span-2">Shipping & Payment</h3><div><label class="lbl">Flat shipping (₹)</label><input name="shipping_fee" type="number" value="${f("shipping_fee")}" class="input"></div><div><label class="lbl">Free shipping above (₹)</label><input name="free_shipping_above" type="number" value="${f("free_shipping_above")}" class="input"></div><div><label class="lbl">Delivery estimate (days)</label><input name="delivery_days" type="number" value="${f("delivery_days")}" class="input"></div><label class="flex items-center gap-2"><input type="checkbox" name="cod_enabled" ${v.cod_enabled === "1" ? "checked" : ""}> Enable COD</label></div>
    <div class="bg-white rounded-2xl border border-gray-100 p-6 grid sm:grid-cols-2 gap-4"><h3 class="font-semibold sm:col-span-2">Invoice / GST</h3><div><label class="lbl">Seller name</label><input name="seller_name" value="${f("seller_name")}" class="input"></div><div><label class="lbl">GSTIN</label><input name="gst_number" value="${f("gst_number")}" class="input"></div><div class="sm:col-span-2"><label class="lbl">Seller address</label><input name="seller_address" value="${f("seller_address")}" class="input"></div><div><label class="lbl">GST rate (%)</label><input name="gst_rate" type="number" value="${f("gst_rate")}" class="input"></div></div>
    <div class="bg-white rounded-2xl border border-gray-100 p-6 grid sm:grid-cols-2 gap-4"><h3 class="font-semibold sm:col-span-2">SEO & Marketing</h3><div class="sm:col-span-2"><label class="lbl">Meta description</label><textarea name="meta_description" rows="2" class="input">${f("meta_description")}</textarea></div><div><label class="lbl">Google Analytics ID</label><input name="ga_id" value="${f("ga_id")}" class="input"></div><div><label class="lbl">Meta Pixel ID</label><input name="pixel_id" value="${f("pixel_id")}" class="input"></div></div>
    <button class="bg-ink text-white px-7 py-3 rounded-full hover:bg-clay">Save Settings</button></form>`);
}

export function adminOrderView(ctx, { order, items }) {
  const stOpts = ALL_STATUSES.map((s) => `<option value="${s}" ${order.status === s ? "selected" : ""}>${STATUS_LABELS[s]}</option>`).join();
  return shell(ctx, order.order_no, `<div class="flex items-center justify-between"><a href="/admin/orders" class="text-sm text-clay">← All orders</a><a href="/admin/orders/${e(order.order_no)}/invoice" target="_blank" class="text-sm bg-ink text-white px-4 py-2 rounded-full hover:bg-clay">⬇ Invoice / Print</a></div>
    <div class="grid lg:grid-cols-3 gap-5 mt-3"><div class="lg:col-span-2 space-y-5">
      <div class="bg-white rounded-2xl border border-gray-100 p-6"><h2 class="font-semibold mb-4">Items</h2><div class="space-y-3">${items.map((it) => `<div class="flex gap-3 text-sm"><img src="${e(it.image)}" class="w-12 h-14 object-cover rounded-lg"><div class="flex-1"><p class="font-medium">${e(it.name)}</p><p class="text-xs text-gray-500">${[it.size, it.color].filter(Boolean).join(" / ")} · Qty ${it.qty}</p></div><span>${money(it.price * it.qty)}</span></div>`).join("")}</div><div class="border-t border-gray-100 mt-4 pt-3 text-sm max-w-xs ml-auto space-y-1"><div class="flex justify-between"><span class="text-gray-500">Subtotal</span><span>${money(order.subtotal)}</span></div><div class="flex justify-between"><span class="text-gray-500">Shipping</span><span>${money(order.shipping_fee)}</span></div><div class="flex justify-between font-bold text-base"><span>Total</span><span>${money(order.total)}</span></div></div></div>
      <div class="bg-white rounded-2xl border border-gray-100 p-6 text-sm grid sm:grid-cols-2 gap-4"><div><h3 class="font-semibold mb-1">Customer</h3><p class="text-gray-600">${e(order.customer_name)}<br>${e(order.email || "")}<br>📞 ${e(order.phone)}</p></div><div><h3 class="font-semibold mb-1">Ship to</h3><p class="text-gray-600">${e(order.address_line1)}<br>${e(order.city)}, ${e(order.state)} - ${e(order.pincode)}</p></div></div>
    </div><div class="space-y-5">
      <div class="bg-white rounded-2xl border border-gray-100 p-6"><h3 class="font-semibold mb-3">Update Status</h3><form method="post" class="space-y-3"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><input type="hidden" name="action" value="status"><select name="status" class="input">${stOpts}</select><button class="w-full bg-ink text-white py-2.5 rounded-full text-sm hover:bg-clay">Update</button></form></div>
      <div class="bg-white rounded-2xl border border-gray-100 p-6"><h3 class="font-semibold mb-1">Courier / AWB</h3><p class="text-xs text-gray-400 mb-3">Paste the Shiprocket/Delhivery tracking number — customer sees it.</p><form method="post" class="space-y-3"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><input type="hidden" name="action" value="shipping"><input name="courier_name" value="${e(order.courier_name || "")}" placeholder="Courier" class="input"><input name="awb" value="${e(order.awb || "")}" placeholder="AWB / tracking no" class="input"><button class="w-full bg-ink text-white py-2.5 rounded-full text-sm hover:bg-clay">Save Courier</button></form><form method="post" class="mt-3"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><input type="hidden" name="action" value="shiprocket"><button class="w-full border border-ink py-2.5 rounded-full text-sm hover:bg-ink hover:text-white">🚀 Push to Shiprocket</button></form></div>
      <div class="bg-white rounded-2xl border border-gray-100 p-6"><h3 class="font-semibold mb-3">Payment</h3><form method="post" class="space-y-3"><input type="hidden" name="csrf" value="${e(ctx.csrf)}"><input type="hidden" name="action" value="payment"><p class="text-sm text-gray-500">Method: <b>${e((order.payment_method || "").toUpperCase())}</b></p><select name="payment_status" class="input">${["pending", "paid", "failed"].map((s) => `<option value="${s}" ${order.payment_status === s ? "selected" : ""}>${s}</option>`).join("")}</select><button class="w-full border border-gray-200 py-2.5 rounded-full text-sm hover:bg-gray-50">Update Payment</button></form></div>
    </div></div>`);
}
